version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: aiimage_postgres
    environment:
      POSTGRES_DB: aiimage
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5442:5432"  # Changed from 5441 to avoid conflicts with existing app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aiimage"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: aiimage_redis
    ports:
      - "6391:6379"  # Changed from 6390 to avoid conflicts with existing app
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

# 🔒 Security Notes:
# - Change default passwords in production
# - Use environment variables for sensitive data
# - Consider using Docker secrets for production
# - Enable SSL/TLS for database connections in production

