version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aiimage_db
    environment:
      POSTGRES_DB: aiimage
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aiimage_network

  redis:
    image: redis:7-alpine
    container_name: aiimage_redis
    ports:
      - "6390:6379"
    networks:
      - aiimage_network

volumes:
  postgres_data:

networks:
  aiimage_network:
    driver: bridge
